config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#public'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'users#new',     as: :new_organization_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page
    get '(/u/:user_domain)/dashboard/tables/shared/search/:q'             => 'visualizations#index', as: :tables_shared_search
    get '(/u/:user_domain)/dashboard/tables/shared/search/:q/:page'       => 'visualizations#index', as: :tables_shared_search_page
    get '(/u/:user_domain)/dashboard/tables/locked/search/:q'             => 'visualizations#index', as: :tables_locked_search
    get '(/u/:user_domain)/dashboard/tables/locked/search/:q/:page'       => 'visualizations#index', as: :tables_locked_search_page
    get '(/u/:user_domain)/dashboard/tables/mine/search/:q'               => 'visualizations#index', as: :tables_mine_search
    get '(/u/:user_domain)/dashboard/tables/mine/search/:q/:page'         => 'visualizations#index', as: :tables_mine_search_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/search/:q'        => 'visualizations#index', as: :tables_mine_locked_search
    get '(/u/:user_domain)/dashboard/tables/mine/locked/search/:q/:page'  => 'visualizations#index', as: :tables_mine_locked_search_page


    # Visualizations
    get '(/u/:user_domain)/dashboard/visualizations'                            => 'visualizations#index', as: :visualizations_index
    get '(/u/:user_domain)/dashboard/visualizations/:page'                      => 'visualizations#index', as: :visualizations_page
    get '(/u/:user_domain)/dashboard/visualizations/tag/:tag'                   => 'visualizations#index', as: :visualizations_tag
    get '(/u/:user_domain)/dashboard/visualizations/tag/:tag/:page'             => 'visualizations#index', as: :visualizations_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/shared'                     => 'visualizations#index', as: :visualizations_shared
    get '(/u/:user_domain)/dashboard/visualizations/shared/:page'               => 'visualizations#index', as: :visualizations_shared_page
    get '(/u/:user_domain)/dashboard/visualizations/shared/tag/:tag'            => 'visualizations#index', as: :visualizations_shared_tag
    get '(/u/:user_domain)/dashboard/visualizations/shared/tag/:tag/:page'      => 'visualizations#index', as: :visualizations_shared_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/mine'                       => 'visualizations#index', as: :visualizations_mine
    get '(/u/:user_domain)/dashboard/visualizations/mine/:page'                 => 'visualizations#index', as: :visualizations_mine_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/tag/:tag'              => 'visualizations#index', as: :visualizations_mine_tag
    get '(/u/:user_domain)/dashboard/visualizations/mine/tag/:tag/:page'        => 'visualizations#index', as: :visualizations_mine_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked'                => 'visualizations#index', as: :visualizations_mine_locked
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/:page'          => 'visualizations#index', as: :visualizations_mine_locked_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/tag/:tag'       => 'visualizations#index', as: :visualizations_mine_locked_tag
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :visualizations_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/locked'                     => 'visualizations#index', as: :visualizations_locked
    get '(/u/:user_domain)/dashboard/visualizations/locked/:page'               => 'visualizations#index', as: :visualizations_locked_page
    get '(/u/:user_domain)/dashboard/visualizations/locked/tag/:tag'            => 'visualizations#index', as: :visualizations_locked_tag
    get '(/u/:user_domain)/dashboard/visualizations/locked/tag/:tag/:page'      => 'visualizations#index', as: :visualizations_locked_tag_page

    # Visualizations search
    get '(/u/:user_domain)/dashboard/visualizations/search/:q'                    => 'visualizations#index', as: :visualizations_search
    get '(/u/:user_domain)/dashboard/visualizations/search/:q/:page'              => 'visualizations#index', as: :visualizations_search_page
    get '(/u/:user_domain)/dashboard/visualizations/shared/search/:q'             => 'visualizations#index', as: :visualizations_shared_search

app/views/admin/pages/_announcement.html.erb
<div class="announcement">
  <div class="inner">
    Say "Hi" to the public dashboards: the new way to showcase your maps and data. <a href="http://blog.cartodb.com/post/81486919763/new-public-pages-in-cartodb-discover-great-maps-and">Learn more about it</a>.
  </div>
</div>

app/views/admin/pages/_organization_info.html.erb
<div class="info">

  <div class="user-info">

    <div class="avatar">
      <a href="<%= public_visualizations_home_url(user_domain: params[:user_domain]) %>" class="circle">
      <img src="<%= @organization.avatar_url.present? ? @organization.avatar_url : 'http://cartodb.s3.amazonaws.com/static/public_dashboard_default_organization_avatar.png' %>"
        width="128" height="128" />
      </a>
    </div>

    <div class="details">
      <%= content_tag :h2, ( @organization.display_name.present? ? @organization.name : @organization.display_name ) %>

      <%= link_to "@#{@organization.twitter_username}", "http://twitter.com/#{@organization.twitter_username}", :class => :twitter if @organization.twitter_username.present? %>

      <%= content_tag :p, @organization.description if @organization.description.present? %>

      <% if @organization.website.present? %>

        <% if @organization.description.present? || @organization.twitter_username.present?  %>
        <div class="separator"></div>
        <% end %>

        <div class="website"><%= link_to @organization.website.gsub(/https?:\/\//, ""), @organization.website if @organization.website.present? %></div>
      <% end %>
    </div>

    <ul>
      <% if action_name == 'datasets' %>
        <li><h2 class="count" title="<%= @organization.display_name.present? ? @organization.name : @organization.display_name %> dataset<%= @public_org_tables_count == 1 ? '' : 's' %>"><strong><%= @public_org_tables_count %></strong>dataset<%= @public_org_tables_count == 1 ? '' : 's' %></h2></li>
        <li><h2><a href="<%= public_visualizations_home_url(user_domain: params[:user_domain]) %>" class="count" title="<%= @organization.display_name.present? ? @organization.name : @organization.display_name %> visualization<%= @public_org_tables_count == 1 ? '' : 's' %>"><strong><%= @public_org_vis_count %></strong>visualization<%= @public_org_vis_count == 1 ? '' : 's' %></a></h2></li>
      <% else %>
        <li><h2><a href="<%= public_datasets_home_url(user_domain: params[:user_domain]) %>" class="count" title="<%= @organization.display_name.present? ? @organization.name : @organization.display_name %> dataset<%= @public_org_tables_count == 1 ? '' : 's' %>"><strong><%= @public_org_tables_count %></strong>dataset<%= @public_org_tables_count == 1 ? '' : 's' %></a></h2></li>
        <li><h2 class="count" title="<%= @organization.display_name.present? ? @organization.name : @organization.display_name %> dataset<%= @public_org_tables_count == 1 ? '' : 's' %>"><strong><%= @public_org_vis_count %></strong>visualization<%= @public_org_vis_count == 1 ? '' : 's' %></h2></li>
      <% end %>
    </ul>

  </div>

app/views/admin/pages/_tags.html.erb
<% if @tags.size > 0 %>
  <ul class="tags">
    <li><strong>Browse by tag</strong></li>

    <% @tags.each_with_index do |tag, i| %>
      <li<%= " class='#{i == 0 ? "first" : "last" }'" if i == 0 || i == @tags.size - 1 %>>
        <% if params[:tag] && params[:tag] == tag %>
          <% if action_name == 'datasets' %>
          <%= link_to "x", "/datasets", { :class => "close" } %>
          <% else %>
          <%= link_to "x", "/", { :class => "close" } %>

          <h3><%= tag.capitalize.truncate(40) %></h3>
        <% end %>

        <% else %>

          <% if action_name == 'datasets' %>
          <h3><%= link_to tag.capitalize.truncate(40), public_datasets_tag_url(user_domain: params[:user_domain], tag: tag), :rel => "tag"  %></h3>
          <% else %>
          <h3><%= link_to tag.capitalize.truncate(40), public_tag_url(user_domain: params[:user_domain], tag: tag), :rel => "tag"  %></h3>
          <% end %>

        <% end %>
      <% end %>
      </li>
    </ul>
  <% end %>

app/views/admin/pages/_user_info.html.erb
<div class="info">

  <div class="user-info">

    <div class="avatar">
      <a href="<%= public_visualizations_home_url(user_domain: params[:user_domain]) %>" class="circle">
        <img src="<%= @avatar_url %>" />
      </a>
    </div>

    <div class="details">
      <%= content_tag :h2, @name %>

      <%= link_to "@#{@twitter_username}", "http://twitter.com/#{@twitter_username}", :class => :twitter if @twitter_username.present? %>

      <%= content_tag :p, @description if @description.present? %>

      <% if @website.present? %>

        <% if @description.present? || @twitter_username.present?  %>
        <div class="separator"></div>
        <% end %>

        <div class="website"><%= link_to @website_clean, @website %></div>
      <% end %>
    </div>
    <ul>
      <% if action_name == 'datasets' %>
        <li><h2 class="count" title="<%= @name %> dataset<%= @tables_num == 1 ? '' : 's' %>"><strong><%= @tables_num %></strong>dataset<%= @tables_num == 1 ? '' : 's' %></h2></li>
        <li><h2><a href="<%= public_visualizations_home_url(user_domain: params[:user_domain]) %>" class="count"><strong><%= @vis_num %></strong>visualization<%= @vis_num == 1 ? '' : 's' %></a></h2></li>
      <% else %>
        <li><h2 title="<%= @name %> dataset<%= @tables_num == 1 ? '' : 's' %>"><a href="<%= public_datasets_home_url(user_domain: params[:user_domain]) %>" class="count"><strong><%= @tables_num %></strong>dataset<%= @tables_num == 1 ? '' : 's' %></a></h2></li>
        <li><h2 class="count"><strong><%= @vis_num %></strong>visualization<%= @vis_num == 1 ? '' : 's' %></h2></li>
      <% end %>
    </ul>

  </div>

app/views/admin/pages/common_data.html.erb
  <% content_for(:page_title) do %>
    <%= current_user.username %> |
  <% end %>

  <%= content_for(:js) do %>
    <%= javascript_include_tag 'cdb.js', 'models.js', 'templates.js', 'application.js', 'common_data.js' %>
    <script type="text/javascript">
      var username = "<%= current_user.username %>"
      var user_data = <%=raw current_user.data.to_json.html_safe %>;
      var config = <%=raw frontend_config.html_safe %>;
      var mixpanel_token = "<%= Cartodb.config[:mixpanel]['token'] if Cartodb.config[:mixpanel].present? %>";
    </script>
  <% end %>

  <%= content_for(:css) do %>
    <%= stylesheet_link_tag 'common.css', 'dashboard.css', 'common_data.css', :media => 'all' %>
  <% end %>

  <div class="subheader active">
    <div class="inner">
      <h2>Enhance your maps by importing any of these free-to-use helpful datasets</h2>
    </div>
  </div>

  <div class="main_loader">
    <span class="loader"></span>
    <p>Getting datasets...</p>
  </div>

  <div class="content">
    <article class="empty">
      <div class="inner">
        <h3>Oops! There was an error</h3>
        <p>Unfortunately our CartoFante can't show you all the available common datasets, please come back in a while. If the problem persists, don't hesitate to contact us at <a href="mailto:support@cartodb.com">support@cartodb.com</a>.</p>
      </div>
    </article>

    <article class="public_tables">
      <div class="inner">
        <aside class="options"></aside>
        <section class="tables"></section>
      </div>
    </article>

    <article class="support">
      <div class="inner">
        <section class="left">
        <h3>Don’t find what you are looking for?</h3>
        <p>Try in our <a href="https://groups.google.com/forum/#!forum/cartodb" title="CartoDB Google Group">Google Group</a> or in our <a href="http://gis.stackexchange.com/questions/tagged/cartodb">community forums</a>, there may be some users looking forward to helping you.</p>
        </section>
      </div>
    </article>
  </div>

app/views/admin/pages/public.html.erb
<%= content_for(:js) do %>

  <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false&v=3.12"></script>

    <% if !Rails.env.production? %>
      <%= javascript_include_tag 'cdb.js', 'public_dashboard' %>
    <% else %>
      <script src="//cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/cartodb.js"></script>
      <%= javascript_include_tag 'public_dashboard' %>
    <% end %>

  <!--[if lt IE 9]>
  <%= javascript_include_tag "respond.js" %>
  <script>
    document.createElement('header');
    document.createElement('nav');
    document.createElement('footer');
  </script>
  <![endif]-->

<% end %>

<%= content_for(:css) do %>

  <%= stylesheet_link_tag "common", "embeds/public_info", "public_dashboard" %>
  <link rel="stylesheet" href="//cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/themes/css/cartodb.css" />
  <!--[if lte IE 8]>
  <%= stylesheet_link_tag "public_dashboard_ie" %>
  <![endif]-->
<% end %>

<div class="content<%= " empty" if @visualizations.size == 0 %>">

  <div class="inner">
    <%= render(:partial => 'user_info') %>
    <%= render(:partial => 'tags', :locals => {:collection => @tags }) %>
  </div>

  <div class="visualizations">
    <% if @visualizations.size == 0 %>
      <div class="empty_placeholder">
        <%= @name %> doesn't have any public maps
      </div>
    <% end %>

    <% if @visualizations.size > 0 %>
      <ul>
        <% @visualizations.each_with_index do |vis, i| %>
          <li>
            <div class="map-wrapper<%= " headless" if vis[:tags].size == 0 %>">

              <div class="backdrop"></div>
              <div id="map_<%= i %>" class="map"></div>

              <div class="title">
                <h2><a href="<%= public_visualizations_public_map_url(user_domain: params[:user_domain], id: vis[:id]) %>"><%= vis[:title] %></a></h2>
                <p><%= raw (vis[:description] ? vis[:description] : "") %></p>
              </div>
              <div class="gradient"></div>
            </div>

            <% if vis[:tags].size > 0 %>
            <div class="header">
              <% if vis[:tags].size > 0 %>
                <ul class="tags">
                  <% vis[:tags].each do |tag| %>
                    <li><h3><%= link_to tag, public_tag_url(user_domain: params[:user_domain], tag: tag), :rel => "tag" %></h3></li>
                  <% end %>
                </ul>
              <% end %>
              <div class="mapviews"><%= vis[:mapviews] %> Map views</div>
            </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if @visualizations.length > 0 %>
      <div class="pagination">
        <% if @pages > 1 %>

          <% if @pages > 1 && params[:page].to_i > 1 %>
            <% p = params[:page] || 1 %>
            <% if params[:tag] %>
              <a class="prev" href="<%= public_tag_page_url(user_domain: params[:user_domain], tag: params[:tag], page: (p.to_i-1)) %>">Prev</a>
            <% else %>
              <a class="prev" href="<%= public_page_url(user_domain: params[:user_domain], page: (p.to_i-1)) %>">Prev</a>
            <% end %>
          <% end %>

          <ul>
            <% @pages.times do |i| %>
              <% if params[:tag] %>
                <li <%= "class='selected'" if ((!params[:page] && i == 0) || (params[:page].to_i - 1) == i) %>>
                  <a href="<%= public_tag_page_url(user_domain: params[:user_domain], tag: params[:tag], page: (i+1)) %>"></a>
                </li>
              <% else %>
                <li <%= "class='selected'" if ((!params[:page] && i == 0) || (params[:page].to_i - 1) == i) %>>
                  <a href="<%= public_page_url(user_domain: params[:user_domain], page: (i+1)) %>"></a>
                </li>
              <% end %>
            <% end %>
          </ul>

          <% if @pages > 1 && (params[:page].to_i < @pages) %>
            <% p = params[:page] || 1 %>
            <% if params[:tag] %>
              <a class="next" href="<%= public_tag_page_url(user_domain: params[:user_domain], tag: params[:tag], page: (p.to_i+1)) %>">Next</a>
            <% else %>
              <a class="next" href="<%= public_page_url(user_domain: params[:user_domain], page: (p.to_i+1)) %>">Next</a>
            <% end %>
          <% end %>

        <% end %>
      </div>
        <% end %>

  </div>

</div>
</div>

<script>

  $(function() {

    <% urls = [] %>

    <% @visualizations.map do |v| 
      urls.push(
        :url => "//#{request.env['HTTP_HOST']}/api/v2/viz/#{v[:id]}/viz.json",
        :layer_visibility => v[:layers].map{ |layer| { visible: layer.options["visible"] ? true : false } },
      )
    end %>

  var urls = <%= raw urls.to_json %>;

  _.each(urls, function(url, i) {

    var options = {
      title:          false,
      header:         false,
      description:    false,
      search:         false,
      layer_selector: false,
      text:           false,
      image:          false,
      shareable:      false,
      zoom:           false,
      cartodb_logo:   false,
      scrollwheel:    false,
      legends:        false,
      time_slider:    false,
      loader:         false,
      sublayer_options: url.layer_visibility
    };

    <% if !Rails.env.production? %>
        options.no_cdn = true;
    <% end %>

    cartodb.createVis('map_' + i , url.url, options);
  });

  });

</script>

app/views/admin/pages/public_organization.html.erb
<%= content_for(:js) do %>

  <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false&v=3.12"></script>

    <% if !Rails.env.production? %>
      <%= javascript_include_tag 'cdb.js', 'public_dashboard' %>
    <% else %>
      <script src="//cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/cartodb.js"></script>
      <%= javascript_include_tag 'public_dashboard' %>
    <% end %>

  <!--[if lt IE 9]>
  <%= javascript_include_tag "respond.js" %>
  <script>
    document.createElement('header');
    document.createElement('nav');
    document.createElement('footer');
  </script>
  <![endif]-->

<% end %>

<%= content_for(:css) do %>

  <%= stylesheet_link_tag "common", "embeds/public_info", "public_dashboard" %>
  <link rel="stylesheet" href="//cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/themes/css/cartodb.css" />
  <!--[if lte IE 8]>
  <%= stylesheet_link_tag "public_dashboard_ie" %>
  <![endif]-->
<% end %>


<div class="content<%= " empty" if @public_org_visualizations.count == 0 %>">

  <div class="inner">
      <%= render(:partial => 'organization_info') %>
      <%= render(:partial => 'tags', :locals => {:collection => @tags }) %>
  </div>

  <div class="visualizations">
    <% if @public_org_visualizations.count == 0 %>
      <div class="empty_placeholder">
        <%= ( @organization.display_name.present? ? @organization.name : @organization.display_name ) %> doesn't have any public maps
      </div>
    <% end %>

    <% if @public_org_visualizations.count > 0 %>
      <ul>
        <% @public_org_visualizations.each_with_index do |vis, i| %>
          <li>
            <div class="map-wrapper headless">
              <div class="backdrop"></div>
              <div id="map_<%= i %>" class="map"></div>

              <div class="title">
                <h2><a href="<%= public_visualizations_public_map_url(user_domain: vis[:owner], id: vis[:id]) %>"><%= vis[:title] %></a></h2>
                <p><%= raw (vis[:description] ? vis[:description] : "") %></p>
              </div>
              <div class="gradient"></div>
            </div>

            <% if vis[:tags].size > 0 %>
                <div class="header">
                    <% if vis[:tags].size > 0 %>
                        <ul class="tags">
                            <% vis[:tags].each do |tag| %>
                                <li><h3><%= link_to tag, public_tag_url(user_domain: params[:user_domain], tag: tag), :rel => "tag" %></h3></li>
                            <% end %>
                        </ul>
                    <% end %>
                    <div class="mapviews"><%= vis[:mapviews] %> Map views</div>
                </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if @public_org_visualizations.count > 0 %>
      <div class="pagination">
        <% if @pages > 1 %>

          <% if @pages > 1 && params[:page].to_i > 1 %>
            <% p = params[:page] || 1 %>
            <a class="prev" href="<%= public_page_url(user_domain: params[:user_domain], page: (p.to_i-1)) %>">Prev</a>
          <% end %>

          <ul>
            <% @pages.times do |i| %>
              <li <%= "class='selected'" if ((!params[:page] && i == 0) || (params[:page].to_i - 1) == i) %>>
                <a href="<%= public_page_url(user_domain: params[:user_domain], page: (i+1)) %>"></a>
              </li>
            <% end %>
          </ul>

          <% if @pages > 1 && (params[:page].to_i < @pages) %>
            <% p = params[:page] || 1 %>
            <a class="next" href="<%= public_page_url(user_domain: params[:user_domain], page: (p.to_i+1)) %>">Next</a>
          <% end %>

        <% end %>
      </div>
    <% end %>

  </div>

</div>
</div>

<script>

  $(function() {

    <% urls = [] %>

    <% @public_org_visualizations.map do |v| 
      urls.push(
        :url => "//#{request.env['HTTP_HOST']}/api/v2/viz/#{v[:id]}/viz.json",
        :layer_visibility => v[:layers].map{ |layer| { visible: layer.options["visible"] ? true : false } },
      )
    end %>

  var urls = <%= raw urls.to_json %>;

  _.each(urls, function(url, i) {

    var options = {
      title:          false,
      header:         false,
      description:    false,
      search:         false,
      layer_selector: false,
      text:           false,
      image:          false,
      shareable:      false,
      zoom:           false,
      cartodb_logo:   false,
      scrollwheel:    false,
      legends:        false,
      time_slider:    false,
      loader:         false,
      sublayer_options: url.layer_visibility
    };

    <% if !Rails.env.production? %>
      options.no_cdn = true;
    <% end %>

    cartodb.createVis('map_' + i , url.url, options);
  });

  });

</script>