config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#public'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'users#new',     as: :new_organization_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page
    get '(/u/:user_domain)/dashboard/tables/shared/search/:q'             => 'visualizations#index', as: :tables_shared_search
    get '(/u/:user_domain)/dashboard/tables/shared/search/:q/:page'       => 'visualizations#index', as: :tables_shared_search_page
    get '(/u/:user_domain)/dashboard/tables/locked/search/:q'             => 'visualizations#index', as: :tables_locked_search
    get '(/u/:user_domain)/dashboard/tables/locked/search/:q/:page'       => 'visualizations#index', as: :tables_locked_search_page
    get '(/u/:user_domain)/dashboard/tables/mine/search/:q'               => 'visualizations#index', as: :tables_mine_search
    get '(/u/:user_domain)/dashboard/tables/mine/search/:q/:page'         => 'visualizations#index', as: :tables_mine_search_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/search/:q'        => 'visualizations#index', as: :tables_mine_locked_search
    get '(/u/:user_domain)/dashboard/tables/mine/locked/search/:q/:page'  => 'visualizations#index', as: :tables_mine_locked_search_page


    # Visualizations
    get '(/u/:user_domain)/dashboard/visualizations'                            => 'visualizations#index', as: :visualizations_index
    get '(/u/:user_domain)/dashboard/visualizations/:page'                      => 'visualizations#index', as: :visualizations_page
    get '(/u/:user_domain)/dashboard/visualizations/tag/:tag'                   => 'visualizations#index', as: :visualizations_tag
    get '(/u/:user_domain)/dashboard/visualizations/tag/:tag/:page'             => 'visualizations#index', as: :visualizations_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/shared'                     => 'visualizations#index', as: :visualizations_shared
    get '(/u/:user_domain)/dashboard/visualizations/shared/:page'               => 'visualizations#index', as: :visualizations_shared_page
    get '(/u/:user_domain)/dashboard/visualizations/shared/tag/:tag'            => 'visualizations#index', as: :visualizations_shared_tag
    get '(/u/:user_domain)/dashboard/visualizations/shared/tag/:tag/:page'      => 'visualizations#index', as: :visualizations_shared_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/mine'                       => 'visualizations#index', as: :visualizations_mine
    get '(/u/:user_domain)/dashboard/visualizations/mine/:page'                 => 'visualizations#index', as: :visualizations_mine_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/tag/:tag'              => 'visualizations#index', as: :visualizations_mine_tag
    get '(/u/:user_domain)/dashboard/visualizations/mine/tag/:tag/:page'        => 'visualizations#index', as: :visualizations_mine_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked'                => 'visualizations#index', as: :visualizations_mine_locked
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/:page'          => 'visualizations#index', as: :visualizations_mine_locked_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/tag/:tag'       => 'visualizations#index', as: :visualizations_mine_locked_tag
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :visualizations_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/locked'                     => 'visualizations#index', as: :visualizations_locked
    get '(/u/:user_domain)/dashboard/visualizations/locked/:page'               => 'visualizations#index', as: :visualizations_locked_page
    get '(/u/:user_domain)/dashboard/visualizations/locked/tag/:tag'            => 'visualizations#index', as: :visualizations_locked_tag
    get '(/u/:user_domain)/dashboard/visualizations/locked/tag/:tag/:page'      => 'visualizations#index', as: :visualizations_locked_tag_page

    # Visualizations search
    get '(/u/:user_domain)/dashboard/visualizations/search/:q'                    => 'visualizations#index', as: :visualizations_search
    get '(/u/:user_domain)/dashboard/visualizations/search/:q/:page'              => 'visualizations#index', as: :visualizations_search_page
    get '(/u/:user_domain)/dashboard/visualizations/shared/search/:q'             => 'visualizations#index', as: :visualizations_shared_search

app/models/organization/organization_decorator.rb
module CartoDB
  module OrganizationDecorator
    def data(options = {})
      {
        created_at:        self.created_at,
        description:       self.description,
        discus_shortname:  self.discus_shortname,
        display_name:      self.display_name,
        id:                self.id,
        name:              self.name,
        owner: {
          id:         self.owner ? self.owner.id : nil,
          username:   self.owner ? self.owner.username : nil,
          avatar_url: self.owner ? self.owner.avatar_url : nil
        },
        quota_in_bytes:  self.quota_in_bytes,
        api_calls:       self.get_api_calls(from: self.owner.present? ? self.owner.last_billing_cycle : nil, to: Date.today),
        api_calls_quota: self.map_view_quota,
        geocoding: {
          quota:       self.geocoding_quota,
          monthly_use: self.get_geocoding_calls
        },
        twitter: {
          enabled:     self.twitter_datasource_enabled,
          quota:       self.twitter_datasource_quota,
          block_price: self.twitter_datasource_block_price,
          block_size:  self.twitter_datasource_block_size,
          monthly_use: self.get_twitter_imports_count
        },
        seats:             self.seats,
        twitter_username:  self.twitter_username,
        updated_at:        self.updated_at,
        users:             self.users.map { |u|
          {
            id:          u.id,
            username:    u.username,
            avatar_url:  u.avatar_url
          }
        },
        website:           self.website,
        avatar_url:        self.avatar_url
      }
    end
  end
end

app/controllers/admin/organizations_controller.rb
# coding: utf-8
class Admin::OrganizationsController < ApplicationController
  ssl_required :oauth, :api_key, :regenerate_api_key
  before_filter :login_required, :load_organization_and_members

  def show
  end

  def settings
  end

  def settings_update
    attributes = params[:organization]

    if attributes.include?(:avatar_url)
      asset = Asset.new
      asset.raise_on_save_failure = true
      asset.user_id = current_user.id
      asset.asset_file = attributes[:avatar_url]
      asset.kind = Asset::KIND_ORG_AVATAR
      if asset.save
        @organization.avatar_url = asset.public_url
      end
    end

    @organization.website = attributes[:website]
    @organization.description = attributes[:description]
    @organization.display_name = attributes[:display_name]
    @organization.discus_shortname = attributes[:discus_shortname]
    @organization.twitter_username = attributes[:twitter_username]

    @organization.update_in_central
    @organization.save(raise_on_failure: true)

    redirect_to organization_settings_path(user_domain: params[:user_domain]), flash: { success: "Updated successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    flash[:error] = "There was a problem while updating your organization. Please, try again and contact us if the problem persists."
    render action: :settings
  rescue Sequel::ValidationFailed => e
    flash[:error] = e.message
    render action: :settings
  end

  private

  def load_organization_and_members
    @organization = current_user.organization
    @users = current_user.organization.users
    raise RecordNotFound unless @organization.present? && current_user.organization_owner?
  end

end

app/controllers/api/json/organizations_controller.rb
# encoding: utf-8

class Api::Json::OrganizationsController < Api::ApplicationController
  include CartoDB

  if Rails.env.production? || Rails.env.staging?
    ssl_required :show, :users
  end

  # Fetch info from the current user orgranization
  def show
    render json: {}.to_json if current_user.organization.nil?

    render json: current_user.organization.to_poro
  end

  # Return user list of current user organization
  def users
    render json: {}.to_json if current_user.organization.nil?
    
    render json: current_user.organization.to_poro[:users]
  end

end

app/controllers/superadmin/organizations_controller.rb
class Superadmin::OrganizationsController < Superadmin::SuperadminController
  respond_to :json

  ssl_required :show, :create, :update, :destroy, :index if Rails.env.production? || Rails.env.staging?
  before_filter :get_organization, only: [:update, :destroy, :show]

  layout 'application'

  def show
    respond_with(@organization.data(:extended => true))
  end

  def index
    @organizations = (params[:overquota].present? ? Organization.overquota(0.20) : Organization.all)

    respond_with(:superadmin, @organizations.map(&:data))
  end

  def create
    @organization = Organization.new
    @organization.set_fields_from_central(params[:organization], :create)
    if @organization.save && params[:organization][:owner_id].present? && @organization.owner.nil?
      # TODO: move this into a callback or a model method
      uo = CartoDB::UserOrganization.new(@organization.id, params[:organization][:owner_id])
      uo.promote_user_to_admin
    end
    respond_with(:superadmin, @organization)
  end

  def update
    @organization.set_fields_from_central(params[:organization], :update)
    @organization.save
    respond_with(:superadmin, @organization)
  end

  def destroy
    @organization.destroy
    respond_with(:superadmin, @organization)
  end

  private

  def get_organization
    @organization = Organization[params[:id]]
    raise RecordNotFound unless @organization
  end # get_organization

end

app/views/admin/organizations/_aside.html.erb
<div class="head">
  <h3>Your quota</h3>
</div>
<div class="content">
  <ul>
    <li>
      <div class="seats margin5">
        <div class="progress-bar">
          <span class="bar-2 used"></span>
        </div>
        <p class="margin10"><strong><%= "#{current_user.organization.users.count} of #{current_user.organization.seats}" %></strong> users in your account.</p>
      </div>
      <div class="space margin30">
        <div class="progress-bar">
          <span class="bar-2 used"></span>
          <span class="bar-1 available"></span>
          <span class="bar-0 unassigned" style="width:100%"></span>
        </div>
        <p class="margin10">
          <strong><%= number_to_human_size current_user.organization.db_size_in_bytes %> of <%= number_to_human_size current_user.organization.quota_in_bytes %></strong>
        used in your account.
        </p>
        <p class="margin5">
        <strong><%= number_to_human_size(current_user.organization.unassigned_quota) %></strong>
      unassigned.</p>
      </div>
    </li>
    <li>
      <%= link_to "Upgrade your quota", upgrade_url, :class => "button green" %>
    </li>
  </ul>
</div>

app/views/admin/organizations/_settings_account.html.erb
<% if current_user.organization_owner? %>
  <nav class="account-settings">
    <div class="inner">
      <a href="<%= organization_url(user_domain: params[:user_domain]) %>"
         class="<%= 'selected' if ['admin/organizations', 'admin/users'].include?(params[:controller]) && !['settings'].include?(params[:action]) %>">
        <span class="icon organization"></span>
        <span class="info">
          <h2>Manage your seats</h2>
          <p><%= current_user.organization.users.count %> of <%= current_user.organization.seats %> in use</p>
        </span>
      </a>
      <a href="<%= organization_settings_url(user_domain: params[:user_domain]) %>"
         class="<%= 'selected' if ['settings'].include?(params[:action]) %>">
        <span class="icon stats"></span>
        <span class="info">
          <h2>Public dashboard</h2>
          <p>Configuration, logo,...</p>
        </span>
      </a>
      <a href="<%= account_url %>">
        <span class="icon settings"></span>
        <span class="info">
          <h2>Account settings</h2>
          <p>Invoicing, access,...</p>
        </span>
      </a>
    </div>
  </nav>
<% end %>

app/views/admin/organizations/settings.html.erb
<% content_for(:page_title) do %>
  Your organization | Public Dashboard Settings
<% end %>

<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , organization_users = <%= raw @users.map { |u| {
          id: u.id,
          username: u.username,
          quota_in_bytes: u.quota_in_bytes,
          remaining_quota: u.remaining_quota,
          organization_owner: u.organization_owner?
        }}.to_json -%>
      , user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>

<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "settings_account" %>
<% end %>

<%= form_for @organization, url: organization_settings_update_path(user_domain: params[:user_domain]), multipart: true do |form| %>

    <article class="settings">
      <div class="inner">
        <section class="block">
          <div class="head">
            <h2>Your organization public dashboard</h2>
            <%= link_to 'Go to your public page', CartoDB.base_url(@organization.name), :class => "right-link" %>
          </div>

          <div class="content">

            <div class="left-column">

              <div class="row">
                <div class="field field-1">
                  <%= form.label :display_name %>
                  <%= form.text_field :display_name, :class => @organization.errors[:display_name].present? ? 'error' : nil %>
                  <%= form_error_for :display_name, @organization.errors %>
                </div>
              </div>

              <div class="row">
                <div class="field field-2">
                  <%= form.label :website %>
                  <%= form.text_field :website, :class => @organization.errors[:website].present? ? 'error' : nil %>
                  <%= form_error_for :website, @organization.errors %>
                </div>
                <div class="field field-2 logo">
                  <%= form.label :avatar_url, 'COMPANY LOGO' %>
                  <%= form.file_field :avatar_url, :class => @organization.errors[:avatar_url].present? ? 'error' : nil %>
                  <%= form_error_for :avatar_url, @organization.errors %>
                  <div class="avatar">
                    <img class="avatar" src="<%= @organization.avatar_url.present? ? @organization.avatar_url : 'http://cartodb.s3.amazonaws.com/static/public_dashboard_default_organization_avatar.png' %>" />
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="field field-1">
                  <%= form.label :description %>
                  <%= form.text_area :description, :class => @organization.errors[:description].present? ? 'error' : nil %>
                  <%= form_error_for :description, @organization.errors %>
                </div>
              </div>

              <div class="row">
                <div class="field field-2">
                  <%= form.label :twitter_username %>
                  <%= form.text_field :twitter_username, :class => @organization.errors[:twitter_username].present? ? 'error' : nil %>
                  <%= form_error_for :twitter_username, @organization.errors %>
                </div>
              </div>

              <div class="row">
                <div class="field field-2">
                  <%= form.label :discus_shortname %>
                  <%= form.text_field :discus_shortname, :class => @organization.errors[:discus_shortname].present? ? 'error' : nil %>
                  <%= form_error_for :discus_shortname, @organization.errors %>
                </div>
              </div>
            </div>

            <div class="right-column">
              <div class="row">
                <p>These data will be present in the organization public profile.</p>
              </div>
              <div class="row">
                <p>Recommended images should be 128x128 of size.</p>
              </div>
              <div class="row"></div>
              <div class="row"></div>
              <div class="row"></div>
              <div class="row">
                <p class="margin20">Moderate the comments in your organization maps using your Disqus shortname. <a href="#/how-to" class="disqus_help">Here's how</a>.</p>
              </div>
              
            </div>

          </div>

          <div class="foot">
            <%= form.submit 'Save changes', :class => "right grey button new" %>
          </div>

        </section>
      </div>
    </article>

<% end %>

app/views/admin/organizations/show.html.erb
<% content_for(:page_title) do %>
  Your organization |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , organization_users = <%= raw @users.map { |u| {
          id: u.id,
          username: u.username,
          avatar_url: u.avatar_url,
          quota_in_bytes: u.quota_in_bytes,
          remaining_quota: u.remaining_quota,
          organization_owner: u.organization_owner?
        }}.to_json -%>
      , user_data = <%= raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "settings_account" %>
<% end %>

<article>
  <div class="inner">
    <section class="block">
      <div class="head">
        <h2><%= current_user.organization.name.humanize %>'s users</h2>
      </div>
      <ul><%= render :partial => 'shared/flash_message' %></ul>
      <div class="list-head">
        <ul>
          <li><label>username</label></li>
          <li><label>quota</label></li>
        </ul>
      </div>
      <div class="content users_list">
        <ul>
          <% @users.each do |user| -%>
          <li>
            <div class="info">
              <%= link_to user.username, edit_organization_user_path(user_domain: params[:user_domain], id: user.username) %>
              <% if user.organization_owner? %>
                <span class="status owner">OWNER</span>
              <% end %>
            </div>
            <div class="storage">
              <div class="progress-bar"></div>
            </div>
          </li>
          <% end -%>
        </ul>
      </div>
      <div class="foot">
        <% if current_user.organization.seats > @users.count %>
          <%= link_to "Create new user", new_organization_user_path(user_domain: params[:user_domain]), :class => 'right button grey' %>
          <%= link_to "Buy more seats", upgrade_url, :class => 'margin10 underline left' %>
        <% else %>
          <%= link_to "Upgrade your quota", upgrade_url, :class => "button green right" %>
        <% end %>
      </div>
    </section>
  </div>
</article>