config/routes.rb
# encoding: utf-8

# NOTES:
# (/u/:user_domain)                -> This allows support of org-urls (support != enforcement)
# defaults: { dont_rewrite: true } -> Use this to force an individual action to not get rewritten to org-url
# Can be also done at controller source files by using -> skip_before_filter :ensure_org_url_if_org_user

CartoDB::Application.routes.draw do
  # Double use: for user public dashboard AND org dashboard
  root :to => 'admin/pages#public'

  get   '(/u/:user_domain)/login'           => 'sessions#new',     as: :login
  get   '(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout
  match '(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session

  match '/limits' => 'home#limits', as: :limits
  match '/status' => 'home#app_status'

  # OAuth
  match '(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize
  match '(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token
  match '(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token
  get   '(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    get    '(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    put    '(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update
    # Organization users management
    get    '(/u/:user_domain)/organization/users/:id/edit'  => 'users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    put    '(/u/:user_domain)/organization/users/:id'       => 'users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post   '(/u/:user_domain)/organization/users'           => 'users#create',  as: :create_organization_user
    delete '(/u/:user_domain)/organization/users/:id'       => 'users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    get    '(/u/:user_domain)/organization/users/new'       => 'users#new',     as: :new_organization_user

    # search
    get '(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page
    get '(/u/:user_domain)/dashboard/tables/tag/:tag'                   => 'visualizations#index', as: :tables_tag
    get '(/u/:user_domain)/dashboard/tables/tag/:tag/:page'             => 'visualizations#index', as: :tables_tag_page
    get '(/u/:user_domain)/dashboard/tables/shared'                     => 'visualizations#index', as: :tables_shared
    get '(/u/:user_domain)/dashboard/tables/shared/:page'               => 'visualizations#index', as: :tables_shared_page
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag'            => 'visualizations#index', as: :tables_shared_tag
    get '(/u/:user_domain)/dashboard/tables/shared/tag/:tag/:page'      => 'visualizations#index', as: :tables_shared_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine'                       => 'visualizations#index', as: :tables_mine
    get '(/u/:user_domain)/dashboard/tables/mine/:page'                 => 'visualizations#index', as: :tables_mine_page
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag'              => 'visualizations#index', as: :tables_mine_tag
    get '(/u/:user_domain)/dashboard/tables/mine/tag/:tag/:page'        => 'visualizations#index', as: :tables_mine_tag_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked'                => 'visualizations#index', as: :tables_mine_locked
    get '(/u/:user_domain)/dashboard/tables/mine/locked/:page'          => 'visualizations#index', as: :tables_mine_locked_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag'       => 'visualizations#index', as: :tables_mine_locked_tag
    get '(/u/:user_domain)/dashboard/tables/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :tables_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/tables/locked'                     => 'visualizations#index', as: :tables_locked
    get '(/u/:user_domain)/dashboard/tables/locked/:page'               => 'visualizations#index', as: :tables_locked_page
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag'            => 'visualizations#index', as: :tables_locked_tag
    get '(/u/:user_domain)/dashboard/tables/locked/tag/:tag/:page'      => 'visualizations#index', as: :tables_locked_tag_page

    # Tables search
    get '(/u/:user_domain)/dashboard/tables/search/:q'                    => 'visualizations#index', as: :tables_search
    get '(/u/:user_domain)/dashboard/tables/search/:q/:page'              => 'visualizations#index', as: :tables_search_page
    get '(/u/:user_domain)/dashboard/tables/shared/search/:q'             => 'visualizations#index', as: :tables_shared_search
    get '(/u/:user_domain)/dashboard/tables/shared/search/:q/:page'       => 'visualizations#index', as: :tables_shared_search_page
    get '(/u/:user_domain)/dashboard/tables/locked/search/:q'             => 'visualizations#index', as: :tables_locked_search
    get '(/u/:user_domain)/dashboard/tables/locked/search/:q/:page'       => 'visualizations#index', as: :tables_locked_search_page
    get '(/u/:user_domain)/dashboard/tables/mine/search/:q'               => 'visualizations#index', as: :tables_mine_search
    get '(/u/:user_domain)/dashboard/tables/mine/search/:q/:page'         => 'visualizations#index', as: :tables_mine_search_page
    get '(/u/:user_domain)/dashboard/tables/mine/locked/search/:q'        => 'visualizations#index', as: :tables_mine_locked_search
    get '(/u/:user_domain)/dashboard/tables/mine/locked/search/:q/:page'  => 'visualizations#index', as: :tables_mine_locked_search_page


    # Visualizations
    get '(/u/:user_domain)/dashboard/visualizations'                            => 'visualizations#index', as: :visualizations_index
    get '(/u/:user_domain)/dashboard/visualizations/:page'                      => 'visualizations#index', as: :visualizations_page
    get '(/u/:user_domain)/dashboard/visualizations/tag/:tag'                   => 'visualizations#index', as: :visualizations_tag
    get '(/u/:user_domain)/dashboard/visualizations/tag/:tag/:page'             => 'visualizations#index', as: :visualizations_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/shared'                     => 'visualizations#index', as: :visualizations_shared
    get '(/u/:user_domain)/dashboard/visualizations/shared/:page'               => 'visualizations#index', as: :visualizations_shared_page
    get '(/u/:user_domain)/dashboard/visualizations/shared/tag/:tag'            => 'visualizations#index', as: :visualizations_shared_tag
    get '(/u/:user_domain)/dashboard/visualizations/shared/tag/:tag/:page'      => 'visualizations#index', as: :visualizations_shared_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/mine'                       => 'visualizations#index', as: :visualizations_mine
    get '(/u/:user_domain)/dashboard/visualizations/mine/:page'                 => 'visualizations#index', as: :visualizations_mine_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/tag/:tag'              => 'visualizations#index', as: :visualizations_mine_tag
    get '(/u/:user_domain)/dashboard/visualizations/mine/tag/:tag/:page'        => 'visualizations#index', as: :visualizations_mine_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked'                => 'visualizations#index', as: :visualizations_mine_locked
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/:page'          => 'visualizations#index', as: :visualizations_mine_locked_page
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/tag/:tag'       => 'visualizations#index', as: :visualizations_mine_locked_tag
    get '(/u/:user_domain)/dashboard/visualizations/mine/locked/tag/:tag/:page' => 'visualizations#index', as: :visualizations_mine_locked_tag_page
    get '(/u/:user_domain)/dashboard/visualizations/locked'                     => 'visualizations#index', as: :visualizations_locked
    get '(/u/:user_domain)/dashboard/visualizations/locked/:page'               => 'visualizations#index', as: :visualizations_locked_page
    get '(/u/:user_domain)/dashboard/visualizations/locked/tag/:tag'            => 'visualizations#index', as: :visualizations_locked_tag
    get '(/u/:user_domain)/dashboard/visualizations/locked/tag/:tag/:page'      => 'visualizations#index', as: :visualizations_locked_tag_page

    # Visualizations search
    get '(/u/:user_domain)/dashboard/visualizations/search/:q'                    => 'visualizations#index', as: :visualizations_search
    get '(/u/:user_domain)/dashboard/visualizations/search/:q/:page'              => 'visualizations#index', as: :visualizations_search_page
    get '(/u/:user_domain)/dashboard/visualizations/shared/search/:q'             => 'visualizations#index', as: :visualizations_shared_search

app/controllers/admin/users_controller.rb
# coding: utf-8
class Admin::UsersController < ApplicationController
  ssl_required :oauth, :api_key, :regenerate_api_key

  before_filter :login_required, :check_permissions
  before_filter :get_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
    @user.quota_in_bytes = (current_user.organization.unassigned_quota < 100.megabytes ? current_user.organization.unassigned_quota : 100.megabytes)
  end

  def edit
    @show_dashboard_details_flash = session[:show_dashboard_details_flash]
    @show_account_settings_flash = session[:show_account_settings_flash]
    session[:show_dashboard_details_flash] = nil
    session[:show_account_settings_flash] = nil
  end

  def create
    @user = User.new
    @user.set_fields(params[:user], [:username, :email, :password, :quota_in_bytes, :password_confirmation, :twitter_datasource_enabled])
    @user.organization = current_user.organization
    @user.username = "#{@user.username}"
    copy_account_features(current_user, @user)
    @user.save(raise_on_failure: true)
    @user.create_in_central
    redirect_to organization_path(user_domain: params[:user_domain]), flash: { success: "New user created successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    # @user.destroy # destroy is throwing right now
    redirect_to organization_path(@organization), flash:{ error: "There was a problem while creating the user. Please, try again and contact us if the problem persists." }
  rescue Sequel::ValidationFailed => e
    render action: :new
  end

  def update
    attributes = params[:user]
    @user.set_fields(attributes, [:email]) if attributes[:email].present?
    @user.set_fields(attributes, [:quota_in_bytes]) if current_user.organization_owner?

    @user.set_fields(attributes, [:disqus_shortname]) if attributes[:disqus_shortname].present?
    @user.set_fields(attributes, [:name]) if attributes[:name].present?
    @user.set_fields(attributes, [:website]) if attributes[:website].present?
    @user.set_fields(attributes, [:description]) if attributes[:description].present?
    @user.set_fields(attributes, [:twitter_username]) if attributes[:twitter_username].present?

    @user.password = attributes[:password] if attributes[:password].present?
    @user.password_confirmation = attributes[:password_confirmation] if attributes[:password_confirmation].present?
    @user.soft_geocoding_limit = attributes[:soft_geocoding_limit] if attributes[:soft_geocoding_limit].present?
    @user.twitter_datasource_enabled = attributes[:twitter_datasource_enabled] if attributes[:twitter_datasource_enabled].present?
    @user.soft_twitter_datasource_limit = attributes[:soft_twitter_datasource_limit] if attributes[:soft_twitter_datasource_limit].present?
    @user.update_in_central

    session[:show_dashboard_details_flash] = params[:show_dashboard_details_flash].present?
    session[:show_account_settings_flash] = params[:show_account_settings_flash].present?

    @user.save(raise_on_failure: true)

    redirect_to edit_organization_user_path(user_domain: params[:user_domain], id: @user.username), flash: { success: "Updated successfully" }
  rescue CartoDB::CentralCommunicationFailure => e
    flash[:error] = "There was a problem while updating this user. Please, try again and contact us if the problem persists."
    render action: :edit
  rescue Sequel::ValidationFailed => e
    render action: :edit
  end

  def destroy
    @user.destroy
    head :no_content
  rescue CartoDB::CentralCommunicationFailure => e
    flash[:error] = "There was a problem while deleting this user. Please, try again and contact us if the problem persists."
    render action: :show
  end

  private

  def check_permissions
    raise RecordNotFound unless current_user.organization.present?
    raise RecordNotFound unless current_user.organization_owner? || ['edit', 'update'].include?(params[:action])
  end

  def get_user
    @user = current_user.organization.users_dataset.where(username: params[:id]).first
    raise RecordNotFound unless @user
    raise RecordNotFound unless current_user.organization_owner? || current_user == @user
  end

  def copy_account_features(from, to)
    to.set_fields(from, [
      :private_tables_enabled, :sync_tables_enabled, :max_layers, :user_timeout,
      :database_timeout, :geocoding_quota, :map_view_quota, :table_quota, :database_host,
      :period_end_date, :map_view_block_price, :geocoding_block_price, :account_type,
      :twitter_datasource_enabled, :soft_twitter_datasource_limit, :twitter_datasource_quota,
      :twitter_datasource_block_price, :twitter_datasource_block_size
    ])
    to.invite_token = User.make_token
  end
end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < Superadmin::SuperadminController
  respond_to :json

  ssl_required :show, :create, :update, :destroy, :index if Rails.env.production? || Rails.env.staging?
  before_filter :get_user, only: [:update, :destroy, :show, :dump, :data_imports, :data_import]

  layout 'application'

  def show
    respond_with(@user.data(:extended => true))
  end

  def index
    @users = (params[:overquota].present? ? User.overquota(0.20) : User.all)
    respond_with(:superadmin, @users.map(&:data))
  end

  def create
    @user = User.new

    @user.set_fields_from_central(params[:user], :create)
    @user.enabled = true

    @user.save
    respond_with(:superadmin, @user)
  end

  def update
    attributes = params[:user]

    @user.set_fields_from_central(params[:user], :update)

    @user.save
    respond_with(:superadmin, @user)
  end

  def destroy
    @user.destroy
    respond_with(:superadmin, @user)
  end

  def dump
    if Cartodb.config[:users_dumps].nil? || Cartodb.config[:users_dumps]["service"].nil? || Cartodb.config[:users_dumps]["service"]["port"].nil?
      raise "There is not a dump method configured"
    end
    json_data = {database: @user.database_name, username: @user.username}
    response = Typhoeus::Request.new(
      "#{@user.database_host}:#{Cartodb.config[:users_dumps]["service"]["port"]}/scripts/db_dump",
      method: :post,
      headers: { "Content-Type" => "application/json" },
      body: json_data.to_json
    ).run
    parsed_response = JSON.parse(response.body)
    if response.code == 200 && 
       parsed_response['retcode'] == 0 &&
       !parsed_response['return_values']['local_file'].nil? &&
       !parsed_response['return_values']['local_file'].empty? &&
       !parsed_response['return_values']['remote_file'].nil? &&
       !parsed_response['return_values']['remote_file'].empty?
      sa_response = {
        :dumper_response => parsed_response,
        :remote_file => parsed_response['remote_file'],
        :local_file => parsed_response['local_file'],
        :database_host => @user.database_host
      }
      render json: sa_response, status: 200
    else
      sa_response = {
        :dumper_response => parsed_response
      }
      render json: sa_response, status: 400   
    end
  end

  def data_imports
    respond_with(@user.data_imports_dataset.map { |entry|
      {
        id: entry.id,
        data_type: entry.data_type,
        date: entry.updated_at
        }
    })
  end

  def data_import
    data_import = DataImport[params[:data_import_id]]
    respond_with({
                   data: data_import,
                   log: data_import.nil? ? nil : data_import.log.entries
                 })
  end

  private

  def get_user
    @user = User[params[:id]]
    raise RecordNotFound unless @user
  end # get_user

end # Superadmin::UsersController

app/views/admin/users/_form.html.erb
  <script type="text/javascript">
    var organization_users = <%= raw current_user.organization.users.map { |u| {
      id: u.id,
      username: u.username,
      quota_in_bytes: u.quota_in_bytes,
      remaining_quota: u.remaining_quota,
      organization_owner: u.organization_owner?
    }}.to_json -%>;
    <% if !@user.new? %>
    var organization_user_data = <%= raw @user.data.to_json.html_safe -%>;
    <% end %>
  </script>


  <!-- Public dashboard details (name, disqus, twitter, description, etc) -->

  <% if !@user.new? && !current_user.organization_owner? -%>
    <section class="block account">

      <%= form_for @user, url: update_organization_user_path(user_domain: params[:user_domain], id: @user.username) do |f| %>

        <%= f.hidden_field :private_tables_enabled %>
        <%= hidden_field_tag :show_dashboard_details_flash, true %>
        <%= csrf_meta_tags %>

        <div class="head">
          <% if !@user.new? && @user.avatar_url.present? %>
            <img src="<%= @user.avatar_url %>" alt="<%= @user.username %>" title="<%= @user.username %>" />
          <% end %>
          <h2>Your public dashboard</h2>
        </div>

        <% if @show_dashboard_details_flash %>
          <ul><%= render partial: 'shared/flash_message' %></ul>
        <% end %>

        <div class="content">
          <div class="org-user-form">

            <div class="left-column">
              <div class="row">
                <div class="field field-1">
                  <%= f.label :name, 'Your display name' %>
                  <%= f.text_field :name, :class => @user.errors[:name].present? ? 'error' : nil %>
                  <%= form_error_for :name, @user.errors %>
                </div>
              </div>

              <div class="row">
                <div class="field field-1">
                  <%= f.label :website, 'Your website' %>
                  <%= f.text_field :website, :class => @user.errors[:website].present? ? 'error' : nil %>
                  <%= form_error_for :website, @user.errors %>
                </div>
              </div>

              <div class="row">
                <div class="field field-1">
                  <%= label_tag 'user[description]', 'Your description' %>
                  <%= f.text_area :description %>
                </div>
              </div>

              <div class="row">
                <div class="field field-2">
                  <%= f.label :twitter_username, 'Your twitter username' %>
                  <%= f.text_field :twitter_username, :class => @user.errors[:twitter_username].present? ? 'error' : nil %>
                  <%= form_error_for :twitter_username, @user.errors %>
                </div>
              </div>

              <div class="row">
                <div class="field field-2">
                  <%= f.label :disqus_shortname, 'Your disqus shortname' %>
                  <%= f.text_field :disqus_shortname %>
                </div>
              </div>
            </div>

            <div class="right-column">
              <div class="row"></div>
              <div class="row"></div>
              <div class="row"></div>
              <div class="row"></div>
              <div class="row"></div>
              <div class="row">
                <p class="margin35">Moderate the comments in your maps using your Disqus shortname. <a href="#/how-to" class="disqus_help">Here's how</a>.</p>
              </div>

            </div>

          </div>
        </div>

        <div class="foot">
          <%= f.submit 'Save changes', :class => "right grey button new" %>
        </div>

      <% end %>
    </section>
  <% end %>



  <!-- Account settings (password, email, etc) -->

  <section class="block <%= 'margin40' if !current_user.organization_owner? %>">
    <% if current_user.organization_owner? %>
      <%= link_to "back", organization_url(user_domain: params[:user_domain]), :class => "back" %>
    <% end %>

    <%= form_for @user, url: (@user.new? ? create_organization_user_path(user_domain: params[:user_domain], id: @organization) : update_organization_user_path(user_domain: params[:user_domain], id: @user.username)) do |form| %>

      <%= form.hidden_field :private_tables_enabled %>
      <%= hidden_field_tag :show_account_settings_flash, true %>
      <%= csrf_meta_tags %>

      <div class="head">
        <% if !@user.new? && @user.avatar_url.present? && current_user.organization_owner? %>
          <img src="<%= @user.avatar_url %>" alt="<%= @user.username %>" title="<%= @user.username %>" />
        <% end %>
        <h2>
          <% if @user.new? -%>
            Create new user
          <% elsif current_user.organization_owner? %>
            <%= "#{@user.username} details" %>
          <% else %>
            Your account
          <% end %>
        </h2>
      </div>

      <% if @show_account_settings_flash %>
        <ul><%= render partial: 'shared/flash_message' %></ul>
      <% end %>

      <% if !@user.new? && current_user.organization_owner? -%>
      <div class="content user-details">
        <ul>
          <li><%= @user.tables.count %> tables created</li>
          <li><%= @user.visualization_count %> visualizations created</li>
          <li><%= @user.get_geocoding_calls %> georeferenced rows</li>

          <%#
            It needs to know the limits:
              · quota used < 75% -> ok
              · quota used => 75% && quota used < 95% -> danger
              · quota used => 95% -> boom
          -%>
          <% used_percentage = @user.db_size_in_bytes / @user.quota_in_bytes.to_f -%>
          <% user_type = case used_percentage
          when 0..0.7
            'ok'
          when 0.7..0.9
            'danger'
          else
            'boom'
          end -%>

          <li><strong class="<%= user_type %>"><%= number_to_percentage used_percentage, precision: 2 %></strong> of user quota used</li>
          <li><%= @user.get_api_calls(from: @user.last_billing_cycle, to: Date.today).sum %> map views this month</li>
          <li>Last access: <%= "#{distance_of_time_in_words_to_now(@user.get_last_active_time)} ago" rescue "--" %></li>
        </ul>
      </div>
      <% end %>

      <div class="content">
        <div class="org-user-form">

          <div class="left-column">
            <div class="row">
              <div class="field field-2">
                <%= form.label :username %>
                <%= form.text_field :username, :class => @user.errors[:username].present? ? 'error' : nil, :disabled => !@user.new? %>
                <%= form_error_for :username, @user.errors %>
              </div>
            </div>

            <div class="row">
              <div class="field field-2">
                <%= form.label :email %>
                <%= form.text_field :email, :class => @user.errors[:email].present? ? 'error' : nil %>
                <%= form_error_for :email, @user.errors %>
              </div>
            </div>

            <div class="row">
              <div class="field field-2">
                <%= label_tag 'user[password]', 'New password' %>
                <%= password_field_tag 'user[password]', nil, :class => @user.errors[:password].present? ? 'error' : nil %>
                <%= form_error_for :password, @user.errors %>
              </div>
              <div class="field field-2">
                <%= label_tag 'user[password_confirmation]', 'Confirm password' %>
                <%= password_field_tag 'user[password_confirmation]', nil, :class => @user.errors[:password].present? ? 'error' : nil %>
                <%= form_error_for :password_confirmation, @user.errors %>
              </div>
            </div>

            <% if current_user.organization_owner? -%>
              <div class="row">
                <div class="field field-1">
                  <label>
                    <% if @user.new? -%>
                      New user will have
                    <% else %>
                      <%= @user.username %> has
                    <% end %>
                    <strong><%= number_to_human_size(@user.quota_in_bytes) %> assigned</strong> -
                    <a href="#/change-quota" class="change_quota">change</a>
                  </label>
                  <div class="progress-bar"></div>
                  <%= form.hidden_field :quota_in_bytes, :class => @user.errors[:quota_in_bytes].present? ? 'error' : nil, :id => "user_quota" %>
                  <%= form_error_for :quota_in_bytes, @user.errors %>
                </div>
              </div>

              <!-- USER EXTRAS -->
                <div class="extras margin20">
                  <div class="row">
                    <div class="field field-1">
                      <label class="bottom-border">EXTRAS</label>
                      <ul class="extras">
                        <li>
                          <span class="light">Allow extra geocodings</span>
                          <div><%= form.check_box :soft_geocoding_limit %></div>
                        </li>
                        <% if (Cartodb.config[:datasource_search].present?) %>
                          <li>
                            <span class="light">Allow extra tweets</span>
                            <div><%= form.check_box :soft_twitter_datasource_limit %></div>
                          </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>

            <% end -%>
          </div>

          <div class="right-column">
            <div class="row">
              <p>Subdomain cannot be changed</p>
            </div>
            <div class="row">
              <p>
                <% unless @user.new? -%>
                  <% if current_user.organization_owner? -%>
                    This user
                    <%= @user.new? ? "will enter" : "enters" %>
                  <% else %>
                    You enter
                  <% end %>
                  through <%= link_to "#{current_user.organization.name}#{Cartodb.config[:session_domain]}/u/#{@user.username}", "http://#{current_user.organization.name}#{Cartodb.config[:session_domain]}/u/#{@user.username}" %></p>
                <% end -%>
            </div>

            <% if current_user.organization_owner? -%>
              <div class="row">
                <% if false %><p>Or <a href="#/generate-pass" class="pass-generator">generate</a> a random password for this user</p><% end %>
              </div>
              <div class="row">
                <p>Do you need more quota? <%= link_to 'Upgrade your account', upgrade_url %></p>
              </div>
            <% end %>
          </div>

        </div>
      </div>

      <div class="foot">
        <% if !@user.new? -%>
          <%= link_to("delete this user", delete_organization_user_path(user_domain: params[:user_domain], id: @user.username), :class => "left delete red margin15") if current_user.organization_owner? %>
          <%= form.submit 'Save changes', :class => "right grey button new" %>
        <% else %>
          <%= form.submit 'Create user', :class => "right grey button new" %>
        <% end %>
      </div>

    <% end %>
  </section>

app/views/admin/users/edit.html.erb
<% content_for(:page_title) do %>
  Edit user information |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , user_data = <%=raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "admin/organizations/settings_account" %>
<% end %>

<article>
  <div class="inner">
    <%= render partial: 'form' %>
  </div>
</article>

app/views/admin/users/new.html.erb
<% content_for(:page_title) do %>
  Add a new user |
<% end %>
<%= content_for(:js) do %>
  <%= javascript_include_tag 'cdb.js', 'application.js', 'models.js', 'organization.js', 'templates.js' %>
  <script type="text/javascript">
    var username = "<%= current_user.username %>"
      , type = "oauth"
      , config = <%=raw frontend_config.html_safe %>
      , organization_quota = {
          seats: <%= current_user.organization.seats %>,
          quota_in_bytes: <%= current_user.organization.quota_in_bytes %>
        }
      , user_data = <%=raw current_user.data.to_json.html_safe %>;
  </script>
<% end %>
<%= content_for(:css) do %>
  <%= stylesheet_link_tag 'common.css', 'organization.css', :media => 'all' %>
<% end %>

<%= content_for(:account_settings) do %>
  <%= render partial: "admin/organizations/settings_account" %>
<% end %>

<article>
  <div class="inner">
    <%= render partial: 'form' %>
  </div>
</article>